CREATE DATABASE QLNS
ON (
	NAME= QLNS_dat,
	FILENAME= 'D:\QLNS_dat.mdf',
	SIZE = 10,
    MAXSIZE = 50,
    FILEGROWTH = 5
)
LOG ON (
	NAME= QLNS_log,
	FILENAME= 'D:\QLNS_log.ldf',
	SIZE = 5,
    MAXSIZE = 25,
    FILEGROWTH = 5
)
GO
USE QLNS
--USE master
--DROP DATABASE QLNS
--DROP TABLE TrinhDo
GO
CREATE TABLE TrinhDo (
	MaTD INT IDENTITY(1,1) PRIMARY KEY,
	TenTD NVARCHAR(255),
)

CREATE TABLE PhongBan (
	MaPB INT IDENTITY(1,1) PRIMARY KEY,
	TenPB NVARCHAR(255)
)

CREATE TABLE ChucVu (
	MaCV INT IDENTITY(1,1) PRIMARY KEY,
	TenCV NVARCHAR(255)
)

CREATE TABLE DanToc (
	MaDT INT IDENTITY(1,1) PRIMARY KEY,
	TenDT NVARCHAR(50) UNIQUE,
)

CREATE TABLE TonGiao (
	MaTG INT IDENTITY(1,1) PRIMARY KEY,
	TenTG NVARCHAR(50) UNIQUE,
)

CREATE TABLE CongTy (
	MaCTY INT IDENTITY(1,1) PRIMARY KEY,
	TenCTY NVARCHAR(50),
	DienThoai NVARCHAR(50),
	Email NVARCHAR(255),
	DiaChi NVARCHAR(255)
)

CREATE TABLE NhanVien (
	MaNV INT IDENTITY(1,1) PRIMARY KEY,
	MaDT INT,
	MaTG INT,
	MaTD INT,
	MaPB INT,
	MaCV INT,
	MaCTY INT,
	HoTen NVARCHAR(50),
	GioiTinh BIT,
	NgaySinh DATE,
	DiaChi NVARCHAR(255),
	CCCD NVARCHAR(20),
	QueQuan NVARCHAR(255),
	NoiOHienTai NVARCHAR(255),
	DienThoai NVARCHAR(10),
	HinhAnh VARBINARY(max),
	FOREIGN KEY (MaDT) REFERENCES DanToc(MaDT),
	FOREIGN KEY (MaTG) REFERENCES TonGiao(MaTG),
	FOREIGN KEY (MaTD) REFERENCES TrinhDo(MaTD),
	FOREIGN KEY (MaPB) REFERENCES PhongBan(MaPB),
	FOREIGN KEY (MaCV) REFERENCES ChucVu(MaCV),
	FOREIGN KEY (MaCTY) REFERENCES CongTy(MaCTY),
)
-- drop table HopDong
CREATE TABLE HopDong (
	SoHD INT PRIMARY KEY,
	NgayKy DATE,
	NgayBatDau DATE,
	NgayKetThuc DATE,
	LanKy NVARCHAR(10),
	ThoiGian NVARCHAR(10),
	HeSoLuong FLOAT,
	NoiDung NVARCHAR(MAX),
	MaNV INT REFERENCES NhanVien(MaNV)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)

--ALTER TABLE NhanVIen
--ADD MaTonGiao INT,
--FOREIGN KEY (MaTonGiao) REFERENCES TonGiao(MaTonGiao);

CREATE TABLE TaiKhoan (
	TaiKhoan NVARCHAR(50) PRIMARY KEY,
	MatKhau NVARCHAR(20),
)

CREATE TABLE KhenThuong (
	SoQD INT PRIMARY KEY,
	NgayQD DATE,
	LyDo NVARCHAR(100),
	NoiDung NVARCHAR(100),
	MaNV INT REFERENCES NhanVien(MaNV)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)

CREATE TABLE KyLuat (
	SoQD INT PRIMARY KEY,
	NgayQD DATE,
	NgayKetThuc DATE,
	LyDo NVARCHAR(100),
	NoiDung NVARCHAR(100),
	MaNV INT REFERENCES NhanVien(MaNV)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)

CREATE TABLE LuanChuyen (
	SoQD INT PRIMARY KEY,
	NgayQD DATE,
	MaNV INT REFERENCES NhanVien(MaNV) 
	ON UPDATE CASCADE ON DELETE CASCADE,
	PBCu INT REFERENCES PhongBan(MaPB),
	PBMoi INT REFERENCES PhongBan(MaPB),
	LyDo NVARCHAR(100),
	GhiChu NVARCHAR(100)
)

CREATE TABLE ThoiViec (
	SoQD INT PRIMARY KEY,
	NgayNopDon DATE,
	NgayNghi DATE,
	MaNV INT REFERENCES NhanVien(MaNV)
	ON UPDATE CASCADE ON DELETE CASCADE,
	LyDo NVARCHAR(100),
	GhiChu NVARCHAR(100)
)

CREATE TABLE LoaiCa (
	MaLoaiCa INT IDENTITY(1,1) PRIMARY KEY,
	TenLoaiCa NVARCHAR(100),
	HeSo FLOAT
)

CREATE TABLE LoaiCong (
	MaLoaiCong INT IDENTITY(1,1) PRIMARY KEY,
	TenLoaiCong NVARCHAR(100),
	HeSo FLOAT
)

CREATE TABLE PhuCap (
	MaPhuCap INT IDENTITY(1,1) PRIMARY KEY,
	TenPhuCap NVARCHAR(100),
	SoTien FLOAT
)

CREATE TABLE ChiTietNhanPhuCap (
	MaCTPC INT IDENTITY(1,1) PRIMARY KEY,
	MaNV INT REFERENCES NhanVien(MaNV) ON UPDATE CASCADE ON DELETE CASCADE,
	MaPhuCap INT REFERENCES PhuCap(MaPhuCap) ON UPDATE CASCADE ON DELETE CASCADE,
	NgayGhiPhieu DATE,
	NgayNhanPhuCap DATE,
	GhiChu NVARCHAR(100),
)

CREATE TABLE UngLuong (
	MaUngLuong INT IDENTITY(1,1) PRIMARY KEY,
	MaNV INT REFERENCES NhanVien(MaNV) ON UPDATE CASCADE ON DELETE CASCADE,
	NgayGhiPhieu DATE,
	NgayUngLuong DATE,
	SoTien DECIMAL(18,2),
	GhiChu NVARCHAR(100)
)
-- Test

INSERT INTO TaiKhoan
VALUES ('admin', 'admin')

INSERT INTO DanToc (TenDT)
VALUES ('Kinh')

INSERT INTO TonGiao (TenTG)
VALUES (N'Không')

INSERT INTO TrinhDo (TenTD)
VALUES ('12/12'), (N'Cao đẳng'), (N'Đại học')

INSERT INTO PhongBan (TenPB)
VALUES ('IT'), (N'Quản lý'), (N'Nhân sự')

INSERT INTO ChucVu(TenCV)
VALUES (N'Nhân viên'), (N'Trưởng phòng')

INSERT INTO CongTy(TenCTY, DienThoai, Email, DiaChi)
VALUES (N'CTY TNHH Hiền Phát Vi Na', '02513511610', 'gashienphat1979@gmail.com', N'Quốc lộ 51, An Phước, Long Thành, Đồng Nai')

INSERT INTO LoaiCong (TenLoaiCong, HeSo)
VALUES (N'Công ngày thường', 1), (N'Công ngày lễ', 1.5), (N'Công ngày tết tây', 1.5), (N'Công ngày tết nguyên đán', 2)

INSERT INTO LoaiCa (TenLoaiCa, HeSo)
VALUES (N'Ca đêm', 1.4), (N'Ca sáng', 1), (N'Ca chiều', 1)

INSERT INTO PhuCap (TenPhuCap, SoTien)
VALUES (N'Xăng xe', 800000), (N'Điện thoại', 100000)

SELECT NV.MaNV, DT.TenDT, TG.TenTG, TD.TenTD, PB.TenPB, CV.TenCV, CTY.TenCTY, NV.HoTen, NV.GioiTinh, NV.NgaySinh, NV.DiaChi, NV.CCCD, NV.QueQuan, NV.NoiOHienTai, NV.DienThoai, NV.HinhAnh  
FROM NhanVien NV
INNER JOIN DanToc DT ON NV.MaDT = DT.MaDT
INNER JOIN TonGiao TG ON NV.MaTG = TG.MaTG
INNER JOIN TrinhDo TD ON NV.MaTD = TD.MaTD 
INNER JOIN PhongBan PB ON NV.MaPB = PB.MaPB 
INNER JOIN ChucVu CV ON NV.MaCV = CV.MaCV 
INNER JOIN CongTy CTY ON NV.MaCTY = CTY.MaCTY

SELECT lc.SoQD, lc.NgayQD, nv.MaNV, nv.HoTen, pbCu.TenPB AS PBCu, pbMoi.TenPB AS PBMoi, lc.LyDo, lc.GhiChu
FROM LuanChuyen lc
JOIN NhanVien nv ON lc.MaNV = nv.MaNV
JOIN PhongBan pbCu ON lc.PBCu = pbCu.MaPB
JOIN PhongBan pbMoi ON lc.PBMoi = pbMoi.MaPB

SELECT KT.SoQD, NV.HoTen, KT.NgayQD, KT.LyDo, KT.NoiDung FROM KhenThuong KT INNER JOIN NhanVien NV ON NV.MaNV = KT.MaNV

SELECT tv.SoQD, tv.NgayNopDon, tv.NgayNghi, nv.MaNV, nv.HoTen, tv.LyDo, tv.GhiChu FROM ThoiViec tv JOIN NhanVien nv ON tv.MaNV = nv.MaNV

SELECT CT.MaCTPC, NV.HoTen, PC.TenPhuCap, CT.NgayGhiPhieu, CT.NgayNhanPhuCap, CT.GhiChu FROM ChiTietNhanPhuCap CT JOIN NhanVien NV ON CT.MaNV = NV.MaNV JOIN PhuCap PC ON CT.MaPhuCap = PC.MaPhuCap